services:
  cpp_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: